# Travis CI Configuration File

# Tell Travis CI we're using PHP
language: php

php:
  - 5.5
  - 5.4
  - 5.5
  - 5.6
  - 7.0
  - 7.2
  - nightly
  
# Build matrix options
matrix:
  allow_failures:
    - php: nightly
  fast_finish: true

script: php class-linkshorter.php
